### ISSUE TITLE
Meeting ID

### ISSUE THREAD

**Issue by Siddharth1India** [videosdk-live/videosdk-rtc-javascript-sdk-example#11]
I keep getting error:
`Uncaught (in promise) Error: 'meetingId' is empty, please verify it or generate new meetingId using the API.` 

Isn't it supposed to generate one by itself?

**Comment by nickgraffis** [comment]
Was running into some confusion. To clarify, if someone is having trouble getting the new meeting api to work. You need a token, NOT an API Key, and you can generate the token temp form the dashboard.

https://docs.videosdk.live/javascript/guide/video-and-audio-calling-api-sdk/run-a-sample-javascript-project

**Comment by rajansurani** [comment]
@nickgraffis You can use token generated from the dashboard in the testing environment. It recommended using authentication server which generates token to reduce the chance of your credentials being misused
