### ISSUE TITLE
switch camera during meeting

### ISSUE THREAD

**Issue by bitevio** [videosdk-live/videosdk-rtc-javascript-sdk-example#12]
How to switch camera ( Face or back during meeting )
i'used meeting.changeWebcam(deviceId) ,  but nothing happens !!!!

**Comment by rajansurani** [comment]
You will have to pass the deviceId for the camera you want to use using the meeting.changeWebcam() methods.

Here are the docs:
https://docs.videosdk.live/javascript/guide/video-and-audio-calling-api-sdk/features/camera-controls#enable-disable-and-switch-webcam
