### ISSUE TITLE
Cannot read properties of undefined (reading 'getUserMedia')

### ISSUE THREAD

**Issue by qaisarshabbir** [videosdk-live/videosdk-rtc-javascript-sdk-example#16]
Got this error, when click on the mic or camera button. Any help to resolve this issue

**Comment by rajansurani** [comment]
@qaisarshabbir Can you share on which browser you are testing and also share the error screenshot

**Comment by qaisarshabbir** [comment]
I am using the chrome browser. Below is the URL of my test call. You can see the error details in its console

http://3.29.18.15/admin/start_call/461

**Comment by rajansurani** [comment]
@qaisarshabbir To use Audio and Video in the browser, the website should be secured. 
Once you add SSL to your site, the issue should be resolved.

**Comment by qaisarshabbir** [comment]
Thanks,
