### ISSUE TITLE
Differences from quick start documents

### ISSUE THREAD

**Issue by hmmhmmhm** [videosdk-live/videosdk-rtc-javascript-sdk-example#18]
![image](https://github.com/videosdk-live/videosdk-rtc-javascript-sdk-example/assets/38493722/8c363407-cb6d-4828-92d2-259d2daeaea6)

Perhaps it should rename `.config.example.js` or modify the contents of the document.
(Because there is no dot in the name of the template file now.)

**Comment by hmmhmmhm** [comment]
<img width="176" alt="스크린샷 2023-06-16 오후 3 26 58" src="https://github.com/videosdk-live/videosdk-rtc-javascript-sdk-example/assets/38493722/3975411e-7402-4bc1-b817-b890a51f70e7">

I think we should subtract . from all the examples.

**Comment by ahmedbhesaniya97** [comment]
@hmmhmmhm 
Thanks for raising it, will fix it

**Comment by ahmedbhesaniya97** [comment]
@hmmhmmhm,
Please check, it is resolved.

**Comment by hmmhmmhm** [comment]
it resolved! thx!
