### ISSUE TITLE
Mic and Camera enable requires some code refactoring

### ISSUE THREAD

**Issue by arjun-kava** [videosdk-live/videosdk-rtc-javascript-sdk-example#9]
Mic toggle button displays action instead of status.

**Comment by qaisarshabbir** [comment]
How I enable mic and camera in Javascript prebuild SDK?

**Comment by arjun-kava** [comment]
Hey, @qaisarshabbir 
Here is the doc: https://docs.videosdk.live/prebuilt/guide/prebuilt-video-and-audio-calling/features/mic-controls
Please join our discord server to get more help on this, here it invite: https://discord.gg/videosdk-live-876774498798551130
